global using System.Data;
global using System.Linq.Expressions;
global using Microsoft.Extensions.Logging;
global using MySql.Data.MySqlClient;
global using velocist.Exceptions;
global using velocist.MySqlDataAccess.Core;
global using velocist.MySqlDataAccess.Interfaces;
global using velocist.Reflection;
global using velocist.Serialization.Serialization;
global using velocist.Services.Core.Interfaces;
global using velocist.Utilities.Extensions;
global using velocist.Utilities.Sql;
global using velocist.Utilities.Types;
global using static velocist.LogService.StaticLoggerFactory;