global using System.Data;
global using System.Diagnostics;
global using System.Linq.Expressions;
global using Microsoft.Extensions.Logging;
global using MySql.Data.MySqlClient;
global using velocist.MySqlDataAccess.Core;
global using velocist.MySqlDataAccess.Interfaces;
global using velocist.Services.Core.Interfaces;
global using velocist.Services.Reflection;
global using velocist.Services.Json.Serialization;
global using velocist.Services.Types;
global using static velocist.Services.Log.StaticLoggerFactory;